Add missing keycloak-httpd-client-install RPM installation

diff --git a/tripleo/configure-federation b/tripleo/configure-federation
--- a/tripleo/configure-federation
+++ b/tripleo/configure-federation
@@ -212,6 +212,7 @@ EOF
 
 function client_install {
     local status=0
+    local cmd_client_install="sudo yum -y install keycloak-httpd-client-install"
     local cmd="sudo keycloak-httpd-client-install \
    --client-originate-method registration \
    --mellon-https-port $FED_KEYSTONE_HTTPS_PORT \
@@ -226,16 +227,23 @@ function client_install {
    -l "/v3/OS-FEDERATION/identity_providers/rhsso/protocols/mapped/auth"
 "
     if [ $verbose -ne 0 -o $dry_run -ne 0 ]; then
+	echo $cmd_client_install
         echo $cmd
     fi
     if [ $dry_run -ne 0 ]; then
         return $status
     fi
 
-    $cmd
+    $cmd_client_install
     status=$?
     if [ $status -ne 0 ]; then
-        (>&2 echo -e "ERROR cmd \"$cmd\" failed\nstatus = $status")
+        (>&2 echo -e "ERROR cmd \"$cmd_client_install\" failed\nstatus = $status")
+    else
+	$cmd
+	status=$?
+	if [ $status -ne 0 ]; then
+	    (>&2 echo -e "ERROR cmd \"$cmd\" failed\nstatus = $status")
+	fi
     fi
     return $status
 }
